version : '2'
services:
    jsc:
        image: ebymohan/devsecops:deb
        ports:
            - "8080:8080"
        links:
            - j_mysql


    j_mysql:
        image: joychou/jsc_mysql:latest
        ports:
            - "3306:3306"